pub mod action;
pub mod app;
pub mod app_prompt;
pub mod app_queue;
pub mod app_state;
pub mod battle;
pub mod capabilities;
pub mod clipboard_paste;
pub mod components;
pub mod effect;
pub mod events;
pub mod git_tracker;
pub mod session;
pub mod tab_manager;
pub mod terminal_guard;

pub use action::Action;
pub use app::App;
pub use app_state::{AppState, PerformanceMetrics};
pub use battle::{BattleAgent, BattleResults, BattleSession, BattleState, ShareableResults};
pub use capabilities::AgentCapabilities;
pub use effect::Effect;
pub use events::{AppEvent, InputMode};
pub use git_tracker::{GitTrackerHandle, GitTrackerUpdate};
pub use session::AgentSession;
pub use tab_manager::TabManager;
